### ISSUE TITLE
Team Update

### ISSUE THREAD

**Issue by ujjwall-R** [ProDex-IIT-Kharagpur/Prodex_Website_test#2]
Update Team Section in index.html (after collecting info from current members).

`<section id="team" class="team section-bg">`

If needed, add template.

**Comment by ujjwall-R** [comment]
What do you guys think, should we add template or just add sections/div in html for now(current website)?

**Comment by JebronLames32** [comment]
Assign it to me

**Comment by JebronLames32** [comment]
Have made a pull request @ujjwall-R .
